docker-local/yumreport/review/urls.py
from django.urls import path

from . import views
app_name = 'review'
urlpatterns = [
    path('', views.index, name='index'),
]

docker-local/yumreport/yumreport/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('review/', include('review.urls')),
    path('admin/', admin.site.urls),
]

docker-local/yumreport/review/models.py
import datetime

from django.db import models
from django.utils import timezone
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

docker-local/yumreport/review/views.py
from django.shortcuts import render
from datetime import date
import calendar
from calendar import HTMLCalendar


def index(request, year=date.today().year, month=date.today().month):
    year = int(year)
    month = int(month)
    if year < 1900 or year > 2099: year = date.today().year
    month_name = calendar.month_name[month]
    title = "MyClub Event Calendar - %s %s" % (month_name, year)
    cal = HTMLCalendar().formatmonth(year, month)
    announcements = [
    {
      'date': '8-10-2019', 'announcement': "Club Registrations Open"
    },
    {
      'date': '8-15-2019', 'announcement': "Joe Smith Elected New Club President"
    }
    ]
    # return HttpResponse("<h1>%s</h1><p>%s</p>" % (title, cal))
    return render(request, 'review/calendar_base.html', {'title': title, 'cal': cal,'announcements': announcements})

docker-local/yumreport/review/templates/review/announcements.html
<h2>Announcements</h2>
<table>
    {% for announcement in announcements %}
    <tr>
        <td><strong>{{ announcement.date }}</strong></td>
        <td>{{ announcement.announcement }}</td>
    </tr>
    {% empty %}
    <tr>
       <td><strong>{% now "m-d-y" %}</strong></td>
       <td>No Announcements</td>
   </tr>
   {% endfor %}
</table>

docker-local/yumreport/review/templates/review/calendar_base.html
{% extends 'review/index.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>{% autoescape off %}{{ cal }}{% endautoescape %}</p>
    {% include "review/announcements.html" %}
{% endblock content %}

docker-local/yumreport/review/templates/review/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'review:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

docker-local/yumreport/review/templates/review/index.html
{% load static %}
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ page_title|default:"Untitled Page" }}
       {% endblock title %}
   </title>
   <link href="{% static 'review/main.css' %}" rel="stylesheet" type="text/css">
</head>

<body>
   <div id="wrapper">
       <header id="header">
           <div id="logo"><img src="{% static 'review\images\cat.png' %}" alt="" /></div>
           <div id="top_menu">Home | Calendar | About | Contact</div>
           <div id="topbanner"><img src="{% static 'review\images\cat.png' %}" alt="" /></div>
       </header>
       <aside id="rightsidebar">
           <nav id="nav">
               <ul>
                   <li>Menu 1</li>
                   <li>Menu 2</li>
                   <li>Menu 3</li>
               </ul>
           </nav>
       </aside>
       <section id="main">
           {% block content %}
           <p>Placeholder text in base template. Replace with page content.</p>
           {% endblock content %}
       </section>
       <footer id="footer">Copyright &copy;
           <script type="text/JavaScript">
               document.write(new Date().getFullYear());
           </script> MyClub
       </footer>
    </div>
</body>

</html>

docker-local/yumreport/review/templates/review/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'review:detail' question.id %}">Vote again?</a>